### ISSUE TITLE
ℹ️ Update team README file to include team info

### ISSUE THREAD

**Issue by KenjiPcx** [KenjiPcx/Diabot#20]
Follow this [GitHub Flavored Markdown Spec](https://github.github.com/gfm/) here to learn how to use markdown 

### Useful sections to have 
- Intro
- Team Name
- Team Member
- Project type, purpose & description
- Tools and technologies used

**Comment by lahybris** [comment]
- **Team Name**: DiaBot
- **Team Member**: 
- **Project type** : Prototype Sprint - Healthcare
- **purpose & description** : Setup an experience prototype, based on azure & cognitive services. Prototyping is the process of creating a model or early version of a product in order to test its functionality and feasibility. The process of prototyping typically will be developed in five main stages:

1. Defining the vision: creating an overarching vision for the product and answering key questions such as what problem it solves, who the target market is, and what the anticipated price point will be. This helps determine if it is viable and if the cost of creating a prototype is justified.

2. Focusing on key features: rather than trying to make the prototype identical to the final product, we should focus on one or two key features to test in the prototype. This helps keep the prototype simple and avoids wasting time on unnecessary details.

3. Production

4. Testing and refining: after the initial prototype is created, it should be tested and evaluated to identify any potential issues or areas for improvement. 

5. Presentation: The final stage of the prototyping process is presenting the prototype this helps gauge interest in the product and provides feedback that can be used to refine the design.


- **Tools and technologies used**: Azure ML, Azure DB, Azure Bots,Azure Maps,Azure IoT

**Comment by KenjiPcx** [comment]
@lahybris Can you add a short description about our project into this page 
```
Diabot is a carb logger app to help diabetes patients manage their carbs and glucose level but with a twist, they get to interact with a personal assistant bot, we are taking advantage of chatbots to make carb logger apps more user friendly and accessible
```
Can you change the tolls used as well into
```
CosmosDb, Azure Bot, Azure App Service, Azure App Service Plan, Language Service, Speech Service, .NET Maui, .NET Core
```
And can you format the readme to be like
### Header
body

ie 

### Team Name
Diabot
